on: push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    run:
        uses: actions/checkout@v2.3.2
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        run: composer install --ignore-platform-reqs
        run: php artisan key:generate
        run: php artisan storage:link
        run: chmod -R 777 storage bootstrap/cache
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /